version: "1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres101
    ports:
    - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    privileged: true